[build]
NODE_ENV = "10.15.3"
command = "npm run build"
functions = "src/functions"
publish = "dist"

[dev]
command = "npm run start"

[[redirects]]
from = "/api/*"
status = 200
to = "/.netlify/functions/:splat"

[[redirects]]
from = "/macro-playground"
status = 301
to = "https://fanuc-macro-b.netlify.app"
